Feature Slicing
greenbird/piri pull request #95
Opened 2020-09-21 13:54 UTC by thomasborgen

2020-09-25 13:55 UTC, ChameleonTartu commented on docs/introduction.md
> +    If you have some max length on a database table, then you can use string slicing to make sure the length does not exceed a certain length with the `to` key. Some databases also has for example tw
`to=None` or `to=null`?

2020-09-25 13:57 UTC, ChameleonTartu commented on docs/introduction.md
> +    If you need to take values from end of string, like the 5 last characters, then you can use a negative `from` value to count from the end instead. This works just like pythons slicing functionali
Wouldn't be a link to Python slicing appropriate here?

2020-09-25 13:59 UTC, ChameleonTartu commented on tests/schema/test_slicing.py
> +from returns.pipeline import is_successful
It would be nice to have a single test with negative numbers so that slicing will reverse string.

2020-09-25 14:00 UTC, ChameleonTartu requested changes
@thomasborgen LGTM. There are minor comments regarding the functionality.

2020-09-25 14:17 UTC, thomasborgen commented on tests/schema/test_slicing.py
> +from returns.pipeline import is_successful
Slicing cannot reverse the string. consider:
```python
>>> 'abcdefg'[-3:-5]
''
```
slicing notation actually has one more parameter and that is the `step`. By default its 1, but changing it to -1 reversers the order. so:
```python
>>> 'abcdefg'[-3:-5:-1]
'ed'
```
We can add an issue about this if we need this functionality, but i believe it to be very very nishe. it would also allow you to skip values ie:
```python
>>> 'abcdefg'[::2]
'aceg'
```

I'll add tests with negative values.

2020-09-28 07:57 UTC, ChameleonTartu approved these changes
@thomasborgen パーフェクト!

2020-09-28 07:57 UTC, merged